1.update delete garbage and punctuations tags;
SpeechColab/GigaSpeech pull request #21
Opened 2021-03-16 09:04 UTC by wangyongqing0731

2.rename files;
3. reorganize analyze_meta.py into specialized tools for kaldi

2021-03-16 23:51 UTC, chenguoguo requested changes
Generally looks good to me but left two comments.

2021-03-16 23:51 UTC, chenguoguo commented on toolkits/kaldi/gigaspeech_data_prep.sh
> +  echo "$0: Analyze meta into $corpus_dir"
Analyze --> Extract?

2021-03-16 23:51 UTC, chenguoguo commented on toolkits/kaldi/extract_corpus_for_kaldi.py
>             open(f'{output_dir}/text', 'w') as utt2text, \
What about calling this file extract_meta.py?

2021-03-17 09:58 UTC, dophist commented
LGTM

2021-03-17 09:59 UTC, merged