Add Athena toolkits
SpeechColab/GigaSpeech pull request #56
Opened 2021-07-05 04:03 UTC by shuaijiang

2021-07-05 06:21 UTC, chenguoguo requested changes
Generally looks good but I added some comments.

2021-07-05 06:21 UTC, chenguoguo commented on toolkits/athena/extract_meta.py
> +# Copyright 2021  Xiaomi Corporation (Author: Yongqing Wang)
You might want to add shebang

2021-07-05 06:21 UTC, chenguoguo commented on toolkits/athena/prepare_data.py
> +#!/usr/bin/env bash
This is not bash, is it?

2021-07-06 01:44 UTC, shuaijiang commented on toolkits/athena/prepare_data.py
> +#!/usr/bin/env bash
not bash

2021-07-06 01:44 UTC, shuaijiang commented on toolkits/athena/extract_meta.py
> +# Copyright 2021  Xiaomi Corporation (Author: Yongqing Wang)
sorry

2021-07-14 07:26 UTC, chenguoguo approved these changes
Great, merging this1

2021-07-14 07:26 UTC, merged