Add utt2spk_to_spk2utt
SpeechColab/GigaSpeech pull request #90
Opened 2021-09-27 14:21 UTC by chaisz19

2021-10-12 06:46 UTC, chenguoguo requested changes
Overlooked this PR...

2021-10-12 06:46 UTC, chenguoguo commented on utils/ls_md5.sh
> +  utils/install_jq.sh || exit 1
Add one more line?

```
echo "$0: Attempting jq installation ..."
```

2021-10-12 06:46 UTC, chenguoguo commented on toolkits/kaldi/utt2spk_to_spk2utt.pl
> +#!/usr/bin/env perl
Shall we move it to utils/? And then update the calling script as well?

2022-01-06 04:11 UTC, dophist commented
Is this PR alive ?

2022-01-06 04:11 UTC, dophist commented
Is this PR alive ?

2022-09-10 12:16 UTC, closed without merging